shared:
    image: node:14

jobs:
  A:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
      - set-label: |
          meta set label LONG_LONG_LONG http://abc.com # this will show up in your pipeline events page
  B:
    requires: [~pr, ~commit]
    steps:
      - ok: echo ok
  C:
    requires: [A]
    steps:
      - ok: echo ok
      - timeout: sleep 60;
